name: Deploy Docker Scraper to AWS Lambda

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::816975652129:role/GitHubActionsLambdaRole
          aws-region: us-east-1

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - run: |
          docker build -t job-scraper-engine .
          docker tag job-scraper-engine:latest 816975652129.dkr.ecr.us-east-1.amazonaws.com/job-scraper-repo:latest
          docker push 816975652129.dkr.ecr.us-east-1.amazonaws.com/job-scraper-repo:latest

      - run: aws lambda update-function-code --function-name job-scraper --image-uri 816975652129.dkr.ecr.us-east-1.amazonaws.com/job-scraper-repo:latest